### ISSUE TITLE
Errors when pressing NVDA+alt+right and left arrow with empty list of radio stations

### ISSUE THREAD

**Issue by nvdaes** [DollaR84/radioCenter#2]
When I press NVDA+alt+right or NVDA+alt+left arrow, NVDA 2024.3beta1 registers errors in the log.
[RadioCenterNvda.log](https://github.com/user-attachments/files/16131812/RadioCenterNvda.log)

**Comment by DollaR84** [comment]
Thanks for the error log. I will check and correct it so that this does not happen.

**Comment by DollaR84** [comment]
fixed
